Creating metrics from log messages.
cockroachlabs/visus pull request #102
Opened 2024-04-22 20:37 UTC by sravotto

This change adds the ability of scanning log messages and incrementing counters everytime a log message matches a given regular expression.

2024-04-22 20:37 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachlabs/visus?pullRequest=102) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachlabs/visus?pullRequest=102) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachlabs/visus?pullRequest=102) it.</sub>

2024-05-14 13:41 UTC, BramGruneir requested changes
Good start, but I think there's more to do.

> Reviewed 32 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachlabs/visus/102#-:-NxrKVos3fToxioX55xp:bsly0e5)* status: all files reviewed, 22 unresolved discussions (waiting on @sravotto)

___
*[`internal/cmd/scan/admin.go` line 44 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxmlbhR-JHUAlJm1gOp:-NxmlbhSAcufFG4e4o4r:b-10o17o) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/cmd/scan/admin.go#L44)):*
> ```Go
> 	Name  string
> 	Regex string
> 	Help  string
> ```

alphabetize
___
*[`internal/cmd/scan/admin.go` line 53 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-Nxmlf6H61ED62A5l1c1:-Nxmlf6H61ED62A5l1c2:b-10o17o) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/cmd/scan/admin.go#L53)):*
> ```Go
> 	Format   string
> 	Enabled  bool
> 	Patterns []patternDef
> ```

alphabetize
___
*[`internal/cmd/server/server.go` line 91 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxnRjAk8wk4PKIaojjU:-NxnRjAk8wk4PKIaojjV:b-7hmpks) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/cmd/server/server.go#L91)):*
> ```Go
> 					case syscall.SIGHUP:
> 						log.Info("Refreshing configuration")
> 						if err := metricServer.Refresh(ctx); err != nil {
> ```

Don't want this to exit on fail?
___
*[`internal/http/server.go` line 48 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxnVHifEES2Oa8U8kw3:-NxnVHifEES2Oa8U8kw4:b-syi6ty) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/http/server.go#L48)):*
> ```Go
> 	mu              struct {
> 		sync.Mutex
> 		shutdownCalled bool
> ```

you should use the stopper that bob created.  You can extract it from replicator.  Maybe add a todo.
___
*[`internal/http/server.go` line 190 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxnVWKq5BmQ6Vv2JjDw:-NxnVWKq5BmQ6Vv2JjDx:b-l2rbzt) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/http/server.go#L190)):*
> ```Go
> 
> func (s *serverImpl) Stopped() bool {
> 	s.mu.Lock()
> ```

rlock?
___
*[`internal/metric/server.go` line 18 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrEalfBpwaEK-hF1Zq:-NxrEalfBpwaEK-hF1Zr:bhix63l) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/metric/server.go#L18)):*
> ```Go
> package metric
> 
> import (
> ```

This whole file needs tests!
___
*[`internal/metric/server.go` line 370 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrER9uAno8rGhsDqIR:-NxrER9uAno8rGhsDqIS:b-hsoczq) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/metric/server.go#L370)):*
> ```Go
> // setStopped sets the stopped status returning its current value.
> func (m *metricsServer) setStopped(new bool) bool {
> 	m.mu.RLock()
> ```

rlock?  Shouldn't this be just lock?
___
*[`internal/scanner/scanner.go` line 59 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrI4dF43epQYiWclJi:-NxrI4dF43epQYiWclJj:bb7onj7) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/scanner/scanner.go#L59)):*
> ```Go
> // Config defines the behavior of the scanner
> type Config struct {
> 	FromBeginning bool
> ```

sort
___
*[`internal/scanner/scanner.go` line 98 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrIVXq3Ft0r56Pi8pg:-NxrIVXq3Ft0r56Pi8ph:b-odj5ol) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/scanner/scanner.go#L98)):*
> ```Go
> 	}
> 	switch s.target.Format {
> 	case store.CRDBV2:
> ```

Maybe put the CRDBv2 stuff into it's own file or even it's own package.  Just so it's clear we can add other formats in the future.  By the way, I love that you baked this in.
___
*[`internal/scanner/scanner.go` line 99 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrIGiC1lE2jf2rkn2G:-NxrIGiC1lE2jf2rkn2H:b-i0dv7q) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/scanner/scanner.go#L99)):*
> ```Go
> 	switch s.target.Format {
> 	case store.CRDBV2:
> 		go s.scanCockroachLog()
> ```

why as a subroutine?  Errors won't be caught...  I'm confused by this flow.
It could get stuck, you need some way to know.  You might call this multiple times... not a fan here.

And there's locking too... not good.
___
*[`internal/scanner/scanner_test.go` line 138 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrKORG7nEEfpl6Ekkt:-NxrKORG7nEEfpl6Ekku:b-n5nwiu) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/scanner/scanner_test.go#L138)):*
> ```Go
> 			testVerify(t, tt.want)
> 		})
> 	}
> ```

You need to test some scenarios where the log is blocked, can't be read or other such failure modes.
___
*[`internal/server/config.go` line 24 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrFNnc3Km9cLnx1Gsk:-NxrFNnc3Km9cLnx1Gsl:b-24r59i) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/server/config.go#L24)):*
> ```Go
> 	BindAddr          string        // Address to bind the server to.
> 	BindCert, BindKey string        // Paths to Certificate and Key.
> 	CaCert            string        // Path to the Root CA.
> ```

Sort this list please!  

Do you have a linter as part of the build process?  If not, add it.
___
*[`internal/server/server.go` line 22 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrEsWpC7xEN69SnSRm:-NxrEsWpC7xEN69SnSRn:b-18tm4h) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/server/server.go#L22)):*
> ```Go
> 
> // A Task can be started and stopped.
> type Task interface {
> ```

just use the replicator stopper!

(add it as a todo for later)
___
*[`internal/server/server.go` line 32 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrF-tM6S3ybXaDhmxd:-NxrF-tM6S3ybXaDhmxe:bpero8p) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/server/server.go#L32)):*
> ```Go
> // A Server is a task that has a configuration that can be refreshed.
> type Server interface {
> 	Task
> ```

Why have the separation here?  Why not combine server and task?
___
*[`internal/store/scan.go` line 38 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrGrC-2NRyyiPSNVRu:-NxrGrC-2NRyyiPSNVRv:bb7onj7) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/store/scan.go#L38)):*
> ```Go
> 	Name  string // Name of the pattern, which represents the property being measured.
> 	Regex string // Kind is the type of the pattern.
> 	Help  string // Help to used to describe the pattern.
> ```

sort
___
*[`internal/store/scan.go` line 44 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrGqN5Bels4W0k6ZOY:-NxrGqN6-nwmSZ22WwLm:bb7onj7) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/store/scan.go#L44)):*
> ```Go
> // This struct defines the configuration for the log.
> type Scan struct {
> 	Enabled      bool             // Enabled is true if the patterns needs to be collected.
> ```

sort
___
*[`internal/store/scan.go` line 80 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrH6EGC_Nx_dBlTR8Y:-NxrH6EGC_Nx_dBlTR8Z:bybp8vt) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/store/scan.go#L80)):*
> ```Go
> 		return err
> 	}
> 	defer txn.Commit(ctx)
> ```

can't the commit throw an error?  Shouldn't that be l [...]

2024-05-17 22:11 UTC, sravotto reviewed
Thanks - please take another look. 
I included the stopper - it does simplify the logic to manage the various instance of Servers.
I included additional tests for scanner/collectors, leveraging a in-memory store.

> *[Reviewable](https://reviewable.io/reviews/cockroachlabs/visus/102#-:-Ny7_qIe2DxeWhURQJmy:bej28na)* status: 17 of 43 files reviewed, 21 unresolved discussions (waiting on @BramGruneir)

___
*[`internal/cmd/scan/admin.go` line 44 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxmlbhR-JHUAlJm1gOp:-Nxy4_5C7iDmF1svIzKE:b-896fix) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/cmd/scan/admin.go#L44)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

alphabetize
</blockquote></details>

Done.
___
*[`internal/cmd/scan/admin.go` line 53 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-Nxmlf6H61ED62A5l1c1:-Nxy4aDq0D0Idd4siqM8:b-896fix) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/cmd/scan/admin.go#L53)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

alphabetize
</blockquote></details>

Done.
___
*[`internal/cmd/server/server.go` line 91 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxnRjAk8wk4PKIaojjU:-Ny78tvt65Y8CvR6PwXL:b-f6zzjf) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/cmd/server/server.go#L91)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Don't want this to exit on fail?
</blockquote></details>

I'm thinking that we should just log the error and continue. Existing metric collectors (and scanners) should still work.
___
*[`internal/http/server.go` line 48 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxnVHifEES2Oa8U8kw3:-Ny79D7kCvb8pROd4W5K:b-896fix) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/http/server.go#L48)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

you should use the stopper that bob created.  You can extract it from replicator.  Maybe add a todo.
</blockquote></details>

Done.
___
*[`internal/http/server.go` line 190 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxnVWKq5BmQ6Vv2JjDw:-Nxy4fwVAAlap_tGMLPU:bhh8ylw) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/http/server.go#L190)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

rlock?
</blockquote></details>

Using stopper.
___
*[`internal/metric/server.go` line 18 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrEalfBpwaEK-hF1Zq:-Ny79Ju21-utce4XPOla:b-rwzacy) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/metric/server.go#L18)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

This whole file needs tests!
</blockquote></details>

I added tests for the metric collectors and scanners.
I also separated metrics collectors and scanners so the don't depend on each other.
___
*[`internal/metric/server.go` line 370 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrER9uAno8rGhsDqIR:-Ny7aS09DvjrSM478GL7:b-yn95hf) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/metric/server.go#L370)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

rlock?  Shouldn't this be just lock?
</blockquote></details>

Moved to the scanner package, and using the stopper.
___
*[`internal/scanner/scanner.go` line 59 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrI4dF43epQYiWclJi:-Nxy6Scc3YDmXurf37X5:b-896fix) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/scanner/scanner.go#L59)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

sort
</blockquote></details>

Done.
___
*[`internal/scanner/scanner.go` line 98 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrIVXq3Ft0r56Pi8pg:-Nxy6U6s8HKATq_UPlT_:b-896fix) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/scanner/scanner.go#L98)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Maybe put the CRDBv2 stuff into it's own file or even it's own package.  Just so it's clear we can add other formats in the future.  By the way, I love that you baked this in.
</blockquote></details>

Done.
___
*[`internal/scanner/scanner.go` line 99 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrIGiC1lE2jf2rkn2G:-Ny79mW995AlX-2UfrPj:b-sarywt) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/scanner/scanner.go#L99)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

why as a subroutine?  Errors won't be caught...  I'm confused by this flow.
It could get stuck, you need some way to know.  You might call this multiple times... not a fan here.

And there's locking too... not good.
</blockquote></details>

Using the stopper.
___
*[`internal/scanner/scanner_test.go` line 138 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrKORG7nEEfpl6Ekkt:-Ny7ZHpLAJLejVqPDIFO:b-q9asef) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/scanner/scanner_test.go#L138)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

You need to test some scenarios where the log is blocked, can't be read or other such failure modes.
</blockquote></details>

The tail package takes care of most failures. If the file is not there, it waits to show up.
___
*[`internal/server/config.go` line 24 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrFNnc3Km9cLnx1Gsk:-Nxy6ixB5Kg7NcGjIHCg:b-896fix) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/server/config.go#L24)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Sort this list please!  

Do you have a linter as part of the build process?  If not, add it.
</blockquote></details>

Done.
___
*[`internal/server/server.go` line 22 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrEsWpC7xEN69SnSRm:-Ny7AUEwBXzmqVEgXhmN:b-cm0osv) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/server/server.go#L22)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

just use the replicator stopper!

(add it as a todo for later)
</blockquote></details>

Done.  There is still the Server interface so users can start a server and refresh the configuration. Shutdown is managed by the stopper.
___
*[`internal/server/server.go` line 32 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrF-tM6S3ybXaDhmxd:-Nxy6pQ_9jwC1D1Y4ufN:b-896fix) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/server/server.go#L32)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

Why have the separation here?  Why not combine server and task?
</blockquote></details>

Done.
___
*[`internal/store/scan.go` line 38 at r1](https://reviewable.io/reviews/cockroachlabs/visus/102#-NxrGrC-2NRyyiPSNVRu:-Nxy6sY_DBozFjbsm38G:b-896fix) ([raw file](https://github.com/cockroachlabs/visus/blob/3afa01887ce7fb6ca6a8a345a25ea8b5f5c4c3d9/internal/store/scan.go#L38)):*
<details><summary><i>Previously, BramGrune [...]

2024-05-21 13:17 UTC, BramGruneir requested changes
Please add the stopper as a separate commit.
Actually, I would do this as 3 commits over 2 PRs.

In PR 1:
1) Add the stopper
2) Replace the existing code with the stopper

In PR 2: (on top of commits 1 & 2)
3) (in a separate PR) add the new functionality.

And also as a follow up, add in a github action to run crlfmt and staticcheck and whatever else we run in Replicator.

This has too much in it and you've made new changes in the metrics collection since the last review as well.  

> Reviewed 3 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachlabs/visus/102#-:-NyQH1929AoHBiWEwCgl:b-ncan1v)* status: 20 of 43 files reviewed, 18 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-05-28 16:32 UTC, sravotto commented
This PR was broken down in smaller PRs.

2024-05-28 16:32 UTC, closed without merging